=== PedroGutierrez-1DAW-marca/unidad03/02 - simulacro/ej01.dtd
<!--
  Se estÃƒÂ¡ pensando en crear una aplicaciÃƒÂ³n que ofrezca informaciÃƒÂ³n actual de los partidos de futbol en un dÃƒÂ­a determinado. Las necesidades son las siguientes:

  El documento guardarÃƒÂ¡ datos de varios partidos.
  Cada partido tiene:
    Un id ÃƒÂºnico.
    Nombre de la competiciÃƒÂ³n
      AÃƒÂ±o de la competiciÃƒÂ³n.
      Jornada en su competiciÃƒÂ³n.
    Nombre de equipo local.
      Bandera del equipo local (enlace).
    Nombre de equipo visitante.
      Bandera del equipo visitante (enlace).
    Fecha, hora y minuto de comienzo del partido.
    Resultado.
=>  Estado (terminado/jugando/aplazado)
      Minuto de juego cuando se genera este archivo.
    Canales de retrasmisiÃƒÂ³n (nombre y enlace al logo de cada canal donde se retransmite)
-->
<!ELEMENT partido (id, competicion, elocal, evisitante, resultado, informacion, retransmision)>
  <!ELEMENT id (#PCDATA)>
  <!ELEMENT competicion (nombre, anio, jornada)>
    <!--<!ELEMENT nombre (#PCDATA)>-->
    <!ELEMENT anio (#PCDATA)>
    <!ELEMENT jornada (#PCDATA)>
  <!ELEMENT elocal (nombre, escudo)>
  <!ELEMENT evisitante (nombre, escudo)>
    <!--<!ELEMENT nombre (#PCDATA)>-->
    <!ELEMENT escudo (#PCDATA)>
  <!ELEMENT resultado (glocal, gvisitante)>
    <!ELEMENT glocal (#PCDATA)>
    <!ELEMENT gvisitante (#PCDATA)>
  <!ELEMENT informacion (estado, minutos, inicio)>
    <!ELEMENT estado (#PCDATA)>
    <!ELEMENT minutos (#PCDATA)>
    <!ELEMENT inicio (fecha, hora, minuto)>
      <!ELEMENT fecha (#PCDATA)>
      <!ELEMENT hora (#PCDATA)>
      <!ELEMENT minuto (#PCDATA)>
  <!ELEMENT retransmision (canal+)>
    <!ELEMENT canal (nombre, logo)>
      <!ELEMENT nombre (#PCDATA)>
      <!ELEMENT logo (#PCDATA)>

=== PedroGutierrez-1DAW-marca/unidad03/02 - simulacro/ej01.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Champions league de 2013.
  Jornada: Octavos
  Barcelona – Milan
  Inicio del partido: 20:45 12/03/2013
  Al minuto 65, resultado 1:0
  Se retransmite en Canal + Liga de Campeones
-->
<!DOCTYPE partido PUBLIC "partido" "E:/clase/2013-2014/Marca/03%20-%20XML/02%20-%20simulacro/ej01.dtd">

<partido>
  <id>34927</id>
  <competicion>
    <nombre>Champions league</nombre>
    <anio>2013</anio>
    <jornada>octavos</jornada>
  </competicion>
  <elocal>
    <nombre>Barcelona</nombre>
    <escudo>https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHi-iWwJdQzMan7Wax700KbG43Wx8f47nHaW3WhmuZUMk7wCv-</escudo>
  </elocal>
  <evisitante>
    <nombre>Milan</nombre>
    <escudo>https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTxAkH1O4beCWfHyLjYum1tHzIx3AXPNvqSC1HXUql40sufMCpdUQ</escudo>
  </evisitante>
  <resultado>
    <glocal>1</glocal>
    <gvisitante>0</gvisitante>
  </resultado>
  <informacion>
    <estado>jugando</estado>
    <minutos>65</minutos>
    <inicio>
      <fecha>12/03/2013</fecha>
      <hora>20</hora>
      <minuto>45</minuto>
    </inicio>
  </informacion>
  <retransmision>
    <canal>
      <nombre>Canal + Liga de Campeones</nombre>
      <logo>http://www.vivafutbol.es/images/stories/Fotos_Noticias/00_99/canal_plus_liga_campeones.jpg</logo>
    </canal>
  </retransmision>
</partido>
