=== PedroGutierrez-1DAW-marca/unidad03/01 - inicial/03-ticket-doctype.dtd
<!--
Ejercicio 2 Se desea guardar en formato XML la información relativa a tickets de compra, según las siguientes especificaciones:

  Datos del ticket:
    Código del ticket. Obligatorio.
    Fecha y hora.
    Precio total: Precio sin IVA total, Cantidad IVA y PVP total
    Forma de pago: puede ser en efectivo o con tarjeta.
    Si usa tarjeta: Tipo de tarjeta. 12 asteriscos y los cuatro últimos números de la tarjeta, Nombre del cliente.
  Datos del comercio
    Nombre.
    Dirección completa.
    CIF.
    Teléfono.
  Datos de la compra:
    Línea de compra:
      Nombre del artículo.
      Cantidad.
      Precio unitario (sin IVA).
      IVA
      PVP

Escribe un par de documentos XML que se ajusten a las especificaciones dadas.

-->
<!ELEMENT ticket (tarjeta?, comercio, compra)>
  <!ATTLIST ticket
    codigo CDATA #REQUIRED
    fecha CDATA #IMPLIED
    total CDATA #IMPLIED
    formadepago (efectivo|tarjeta) #IMPLIED>
  <!ELEMENT tarjeta EMPTY>
    <!ATTLIST tarjeta
      tipo (visa|mastercard|americanexpress) #REQUIRED
      numero CDATA #REQUIRED
      cliente CDATA #REQUIRED>
  <!ELEMENT comercio EMPTY>
    <!ATTLIST comercio
      nombre CDATA #REQUIRED
      direccion CDATA #REQUIRED
      cif NMTOKEN #REQUIRED
      telefono NMTOKEN #REQUIRED>
  <!ELEMENT compra (articulo*)>
    <!ELEMENT articulo (#PCDATA)>
      <!ATTLIST articulo
        cantidad NMTOKEN #IMPLIED
        precio NMTOKEN #REQUIRED
        iva (4|8|12|21) #REQUIRED>

=== PedroGutierrez-1DAW-marca/unidad03/01 - inicial/03-ticket-dtd-01.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE ticket PUBLIC "ticket" "E:/clase/2013-2014/Marca/03%20-%20XML/01%20-%20inicial/03-ticket-doctype.dtd">

<ticket codigo="9191893274" fecha="2012/10/23 23:54" total="123" formadepago="tarjeta">
  <tarjeta tipo="visa" numero="************9909" cliente="Paco Perez"></tarjeta>
  <comercio nombre="Dia" direccion="C/ Fuente, 45. Toledo, Toledo" cif="A10101010" telefono="635998998"></comercio>
  <compra>
    <articulo iva="8" precio="0.52">Coliflor</articulo>
    <articulo iva="21" precio="3.21" cantidad="2">Tarta</articulo>
    <articulo iva="4" precio="0.78" cantidad="10">Garrafa de agua</articulo>
    <articulo iva="21" precio="4.97">Abre latas</articulo>
  </compra>
</ticket>
